home_page:
    pattern:  /home
    defaults: { _controller: GcaWebBundle:Home:index }

login_page:
    pattern: /login
    defaults: { _controller: GcaWebBundle:Home:login }.

register_page:
    pattern: /register
    defaults: { _controller: GcaWebBundle:Home:register }

despedida_page:
    pattern: /despedida
    defaults: { _controller: GcaWebBundle:Home:despedida }

check_path:
    pattern:   /login_check
    
logout_page:
    pattern: /logout

