GcaWebBundle_homepage:
    pattern:  /home
    defaults: { _controller: GcaWebBundle:Home:index }

_login_page:
    pattern: /login
    defaults: { _controller: GcaWebBundle:Home:login }.

_register:
    pattern: /register
    defaults: { _controller: GcaWebBundle:Home:register }

check_path:
    pattern:   /login_check
    
logout:
    pattern: /logout

